server:
    port: 8081
    servlet:
        context-path: /api/antecedentes
spring:
    application:
        name: antecedentes-personal
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/clinica-antecedentes
        username: root
        password: danielMysql1@
        driver-class-name: com.mysql.cj.jdbc.Driver
